name: Activity tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Set environment'
        required: true
        default: 'production.org'
        type: choice
        options:
          - production.org
          - production.com
          - production.app.com
          - production.ai
          - staging
          - testing.org
          - testing.com
          - testing.app.com

permissions:
  contents: write
  actions: read

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'



      - name: List all artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Listing all artifacts..."
          gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | {id, name, expired}' | tee artifacts.json

      - name: Download credentials artifact
        uses: actions/download-artifact@v4
        with:
          name: credentials-artifact-${{ env.CURRENT_DATE }}
          path: app/src/main/resources/files/
        continue-on-error: true