name: classTestNew


on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Set environment'
        required: true
        default: 'production.org'
        type: choice
        options:
          - production.org
          - production.com
          - production.ai
          - staging
          - testing.org
          - testing.com
          - testing.app.com

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - run: ./gradlew classTests -Denvironment=$ENVIRONMENT --stacktrace

        # Upload the generated Excel file as an artifact
      - name: Upload Excel file
        uses: actions/upload-artifact@v4
        with:
          name: student-credentials
          path: app/src/main/resources/files/StudentCredentials.xlsx
