name: Everyday tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Set environment'
        required: true
        default: 'production.org'
  schedule:
    - cron: '00 04 * * 0-5' # From Sunday to Friday/

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - name: Build and test with Gradle
        run: ./gradlew addStudents -Denvironment=$ENVIRONMENT
        continue-on-error: true

      - name: Generate Allure Report
        run: ./gradlew allureReport

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-history

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
            allure_results: app/build/allure-results
            gh_pages: gh-pages
            allure_report: app/build/reports/allure-report
            allure_history: allure-history

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir:  allure-history
