name: Everyday tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Set environment'
        required: true
        default: 'production.org'
  schedule:
    - cron: '17 10 * * *'

permissions:
  contents: write

jobs:
  download-history:
    runs-on: ubuntu-latest
    name: Download history
    steps:
      - name: Download historical data
        run: echo "Downloading historical data..."

  tests:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - name: Build and test with Gradle
        run: ./gradlew classTests -Denvironment=$ENVIRONMENT
        continue-on-error: true
      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: app/build/allure-results
          retention-days: 1
          continue-on-error: true
      - name: Allure report create
        run: |
          ./gradlew allureReport
          mkdir -p ${{ github.workspace }}/docs/allureReport
          mv app/build/reports/allure-report/* ${{ github.workspace }}/docs/allureReport
      - name: Allure report get
        run: echo "Allure report live here https://${{ github.repository_owner }}.github.io/${{ github.repository }}/allureReport/index.html"

  generate-report:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - run: allure generate -c app/build/allure-results -o ${{ github.workspace }}/docs/allureReport
      - name: Store generated report
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path: ${{ github.workspace }}/docs/allureReport
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    steps:
      - uses: actions/checkout@v2
      - name: Setup git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: Deploy to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r ${{ github.workspace }}/docs/* .
          git add .
          git commit -m 'Deploy Allure Report'
          git push origin gh-pages --force
