name: Everyday tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Set environment'
        required: true
        default: 'production.org'
  schedule:
    - cron: '17 10 * * *'

jobs:
  download-history:
    runs-on: ubuntu-latest
    name: Download history
    steps:
      - name: Download historical data
        run: echo "Downloading historical data..."

  tests:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - name: Build and test with Gradle
        run: ./gradlew classTests -Denvironment=$ENVIRONMENT
        continue-on-error: true

      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: app/build/allure-results
          retention-days: 1
          continue-on-error: true

  generate-report:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Install Allure command-line tool
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
          sudo tar -zxvf allure-2.23.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure

      - name: Download Allure results artifacts
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: app/build/allure-results

      - name: Generate Allure report
        run: allure generate app/build/allure-results -o _site

      - name: Store generated report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    steps:
      - name: Download Allure report artifacts
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1.2.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          permissions: 'write'
          artifact-dir: '_site'
