name: Everyday tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Set environment'
        required: true
        default: 'production.org'
  schedule:
    - cron: '00 04 * * 0-5' # From Sunday to Friday

permissions:
  contents: write
  pages: write      # to deploy to Pages
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - name: Build and test with Gradle
        run: ./gradlew addStudents -Denvironment=$ENVIRONMENT
        continue-on-error: true

      - name: Generate Allure Report
        run: ./gradlew generateAllureReport
        continue-on-error: true

      - name: Create .nojekyll
        run: echo "" > build/reports/allure-report/.nojekyll

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build/reports/allure-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
