name: Everyday tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Set environment'
        required: true
        default: 'production.org'
  schedule:
    - cron: '00 04 * * 0-5' # From Sunday to Friday

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - name: Build and test with Gradle
        run: ./gradlew addStudents -Denvironment=$ENVIRONMENT
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          ./gradlew allureReport
          mkdir -p allure-results/history
          cp -r allure-report/history/* allure-results/history || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/reports/allure-report
          publish_branch: gh-pages
          keep_files: true # Important to keep historical data

      - name: Update Allure Report History
        run: |
          git fetch --depth=1 origin gh-pages
          git checkout origin/gh-pages -b old-gh-pages
          mkdir -p allure-results/history
          cp -r old-gh-pages/allure-report/history allure-results/history || true
          git checkout ${{ github.ref }}
          git add allure-results/history
          git commit -m "Update historical data for Allure Report"
          git push origin HEAD:gh-pages
